'use client'

import { useState, useEffect } from 'react'
import Link from 'next/link'
import AppHeader from '@/app/components/AppHeader'

type Candidate = { id: number; name: string; onlineCount: number; physicalCount: number | null; isWinner: boolean }
type Position = { id: number; name: string; candidates: Candidate[]; nullVoidCount: number | null }

export default function TallyPage() {
  const [positions, setPositions] = useState<Position[]>([])
  const [locked, setLocked] = useState(false)
  const [released, setReleased] = useState(false)
  const [regionName, setRegionName] = useState('')
  const [physicalInputs, setPhysicalInputs] = useState<Record<string, string>>({})
  const [nullVoidInputs, setNullVoidInputs] = useState<Record<number, string>>({})
  const [error, setError] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const [dataLoading, setDataLoading] = useState(true)
  const [generatingImage, setGeneratingImage] = useState(false)

  useEffect(() => {
    load()
  }, [])

  async function load() {
    setDataLoading(true)
    const res = await fetch('/api/po/tally')
    const data = await res.json()
    if (res.ok) {
      setPositions(data.positions)
      setLocked(data.locked)
      setReleased(data.released)
      setRegionName(data.regionName)
    }
    setDataLoading(false)
  }

  function key(positionId: number, candidateId: number) {
    return `${positionId}-${candidateId}`
  }

  async function generateResultsImage(): Promise<Blob> {
    const width = 900
    const rowH = 32
    const posHeaderH = 44
    const nullVoidRowH = 30
    const posGap = 28
    const headerH = 170
    const footerH = 60
    const padX = 48

    const contentHeight = positions.reduce(
      (sum, p) => sum + posHeaderH + p.candidates.length * rowH + nullVoidRowH + posGap,
      0
    )
    const height = headerH + contentHeight + footerH

    const canvas = document.createElement('canvas')
    canvas.width = width
    canvas.height = height
    const ctx = canvas.getContext('2d')!

    // Background
    ctx.fillStyle = '#f8fafc'
    ctx.fillRect(0, 0, width, height)

    // Header band
    ctx.fillStyle = '#1e3a8a'
    ctx.fillRect(0, 0, width, headerH)

    // Logo (best effort — falls back gracefully if it fails to load)
    try {
      const logo = new Image()
      logo.src = '/icon.png'
      await new Promise<void>((resolve) => {
        logo.onload = () => resolve()
        logo.onerror = () => resolve()
      })
      if (logo.width > 0) {
        ctx.save()
        ctx.beginPath()
        ctx.arc(85, 85, 40, 0, Math.PI * 2)
        ctx.closePath()
        ctx.clip()
        ctx.drawImage(logo, 45, 45, 80, 80)
        ctx.restore()
      }
    } catch {
      // ignore — header text still renders without the logo
    }

    ctx.fillStyle = '#ffffff'
    ctx.textAlign = 'left'
    ctx.font = 'bold 30px Arial, sans-serif'
    ctx.fillText('MTL Workers Union', 145, 75)
    ctx.font = '18px Arial, sans-serif'
    ctx.fillText(`Election Results — ${regionName}`, 145, 105)
    ctx.font = '14px Arial, sans-serif'
    ctx.fillStyle = '#bfdbfe'
    ctx.fillText(
      new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' }),
      145,
      130
    )

    let y = headerH + 44

    for (const p of positions) {
      ctx.fillStyle = '#0f172a'
      ctx.font = 'bold 21px Arial, sans-serif'
      ctx.fillText(p.name, padX, y)
      y += posHeaderH - 6

      const sorted = [...p.candidates].sort(
        (a, b) => b.onlineCount + (b.physicalCount ?? 0) - (a.onlineCount + (a.physicalCount ?? 0))
      )

      for (const c of sorted) {
        const total = c.onlineCount + (c.physicalCount ?? 0)

        if (c.isWinner) {
          ctx.fillStyle = '#dcfce7'
          ctx.fillRect(padX - 12, y - 22, width - padX * 2 + 24, 30)
        }

        ctx.fillStyle = c.isWinner ? '#166534' : '#334155'
        ctx.font = c.isWinner ? 'bold 17px Arial, sans-serif' : '17px Arial, sans-serif'
        ctx.textAlign = 'left'
        ctx.fillText(c.isWinner ? `\u2605 ${c.name}` : c.name, padX, y)

        ctx.textAlign = 'right'
        ctx.fillText(`${total} votes`, width - padX, y)
        ctx.textAlign = 'left'

        y += rowH
      }

      ctx.fillStyle = '#94a3b8'
      ctx.font = '13px Arial, sans-serif'
      ctx.fillText(`Null/void: ${(p as any).nullVoidCount ?? 0}`, padX, y)
      y += posGap
    }

    ctx.fillStyle = '#94a3b8'
    ctx.font = '12px Arial, sans-serif'
    ctx.textAlign = 'center'
    ctx.fillText('Generated by the MTL Workers Union voting system', width / 2, height - 24)

    return new Promise((resolve) => canvas.toBlob((blob) => resolve(blob!), 'image/png'))
  }

  async function shareResults() {
    setGeneratingImage(true)
    setError('')
    try {
      const blob = await generateResultsImage()
      const file = new File([blob], `${regionName.replace(/\s+/g, '-')}-election-results.png`, {
        type: 'image/png'
      })

      const nav = navigator as any
      if (nav.canShare && nav.canShare({ files: [file] })) {
        await nav.share({
          files: [file],
          title: 'Election Results',
          text: `MTL Workers Union — ${regionName} election results`
        })
      } else {
        // Desktop / unsupported browsers: WhatsApp's web link can't attach a
        // file, so download the image and open WhatsApp with instructions.
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = file.name
        a.click()
        URL.revokeObjectURL(url)
        window.open(
          `https://wa.me/?text=${encodeURIComponent(
            'Election results image downloaded — attach it to a WhatsApp chat to share.'
          )}`,
          '_blank'
        )
      }
    } catch (e: any) {
      if (e?.name !== 'AbortError') {
        setError('Could not generate or share the results image.')
      }
    } finally {
      setGeneratingImage(false)
    }
  }

  async function handleSubmit() {
    setError('')
    setSubmitting(true)

    const entries = positions.flatMap((p) =>
      p.candidates.map((c) => ({
        positionId: p.id,
        candidateId: c.id,
        physicalCount: physicalInputs[key(p.id, c.id)] || '0'
      }))
    )
    const nullVoid = positions.map((p) => ({
      positionId: p.id,
      nullCount: nullVoidInputs[p.id] || '0',
      voidCount: '0'
    }))

    const res = await fetch('/api/po/physical-votes', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ entries, nullVoid })
    })
    const data = await res.json()

    if (!res.ok) {
      setError(data.error)
      setSubmitting(false)
      return
    }

    setSubmitting(false)
    load()
  }

  return (
    <div className="min-h-screen bg-slate-50 px-4 py-6 md:px-8 md:py-10">
      <div className="max-w-md md:max-w-5xl mx-auto">
        <AppHeader title="Physical vote entry" backHref="/po" showLogo />

        {locked && (
          <p className="text-sm text-amber-800 bg-amber-50 border border-amber-200 rounded-lg px-3 py-2 mb-4">
            Physical votes have already been entered and locked for this region.
          </p>
        )}

        {dataLoading ? (
          <div className="space-y-4 md:grid md:grid-cols-2 lg:grid-cols-3 md:gap-4 md:space-y-0">
            {[1, 2].map((i) => (
              <div key={i} className="bg-white border border-slate-200 rounded-xl p-4 animate-pulse">
                <div className="h-4 bg-slate-200 rounded w-1/3 mb-4" />
                <div className="flex justify-between items-center mb-3">
                  <div className="h-3 bg-slate-100 rounded w-1/2" />
                  <div className="h-8 w-16 bg-slate-100 rounded-lg" />
                </div>
                <div className="flex justify-between items-center">
                  <div className="h-3 bg-slate-100 rounded w-1/3" />
                  <div className="h-8 w-16 bg-slate-100 rounded-lg" />
                </div>
              </div>
            ))}
          </div>
        ) : (
          <>
            <div className="md:grid md:grid-cols-2 lg:grid-cols-3 md:gap-4">
            {positions.map((p) => (
              <div key={p.id} className="bg-white border border-slate-200 rounded-xl p-4 mb-4 md:mb-0">
                <h2 className="font-medium text-slate-900 mb-3">{p.name}</h2>

                {p.candidates.map((c) => (
                  <div key={c.id} className="flex items-center justify-between mb-2 gap-3">
                    <div className="flex-1">
                      <p className="text-sm text-slate-900">{c.name}</p>
                      <p className="text-xs text-slate-500">Online: {c.onlineCount}</p>
                    </div>
                    <input
                      type="number"
                      min="0"
                      disabled={locked}
                      defaultValue={c.physicalCount ?? ''}
                      onChange={(e) =>
                        setPhysicalInputs((prev) => ({ ...prev, [key(p.id, c.id)]: e.target.value }))
                      }
                      className="w-20 px-2 py-2 border border-slate-300 rounded-lg text-base text-slate-900 text-center disabled:bg-slate-100"
                      placeholder="0"
                    />
                  </div>
                ))}

                <div className="mt-3 pt-3 border-t border-slate-100">
                  <label className="text-xs text-slate-500 block mb-1">Null/void votes</label>
                  <input
                    type="number"
                    min="0"
                    disabled={locked}
                    defaultValue={p.nullVoidCount ?? ''}
                    onChange={(e) =>
                      setNullVoidInputs((prev) => ({ ...prev, [p.id]: e.target.value }))
                    }
                    className="w-full px-2 py-2 border border-slate-300 rounded-lg text-base text-slate-900 text-center disabled:bg-slate-100"
                    placeholder="0"
                  />
                </div>
              </div>
            ))}
            </div>

            {error && (
              <p className="text-sm text-red-600 bg-red-50 border border-red-200 rounded-lg px-3 py-2 mb-4 mt-4">
                {error}
              </p>
            )}

            <div className="md:max-w-sm">
            {!locked && (
              <button
                onClick={handleSubmit}
                disabled={submitting}
                className="w-full mt-4 bg-blue-900 text-white font-medium py-3 rounded-lg active:bg-blue-800 disabled:opacity-60"
              >
                {submitting ? 'Submitting...' : 'Submit physical votes (cannot be edited after)'}
              </button>
            )}

            {!released && (
              <button
                onClick={async () => {
                  const res = await fetch('/api/po/release-results', { method: 'POST' })
                  const data = await res.json()
                  if (!res.ok) { setError(data.error); return }
                  setError('')
                  alert('Results released..')
                  load()
                }}
                disabled={!locked}
                className="w-full mt-4 bg-green-700 text-white font-medium py-3 rounded-lg active:bg-green-800 disabled:opacity-40"
              >
                Release results
              </button>
            )}

            {released && (
              <div className="mt-4 bg-white border border-slate-200 rounded-xl p-4">
                <p className="text-sm font-medium text-slate-900 mb-1">Results released ✓</p>
                <p className="text-xs text-slate-500 mb-3">
                  Generate a branded results image to share with members.
                </p>
                <button
                  onClick={shareResults}
                  disabled={generatingImage}
                  className="w-full bg-green-700 text-white font-medium py-3 rounded-lg active:bg-green-800 disabled:opacity-60 flex items-center justify-center gap-2"
                >
                  {generatingImage ? (
                    'Preparing image...'
                  ) : (
                    <>Share results on WhatsApp</>
                  )}
                </button>
                <p className="text-xs text-slate-400 mt-2">
                  On phones this opens your share sheet with the image attached — pick WhatsApp there.
                  On desktop, it downloads the image and opens WhatsApp Web so you can attach it yourself.
                </p>
              </div>
            )}
            </div>
          </>
        )}
      </div>
    </div>
  )
}